FROM martencz/sphinx-doc:1.0.0
MAINTAINER Martin Malek <github@marten-online.com>

RUN pip install sphinxcontrib-swaggerdoc==0.1.3 \
  sphinxcontrib-apiblueprint==0.9.0 sphinxscript==0.0.6

CMD ["/bin/bash"]

WORKDIR /doc
